services:
  mermaid-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /repo
    command: ['sh', '-lc', 'pnpm install && pnpm dev']
    environment:
      MERMAID_PORT: '9000'
      NODE_OPTIONS: '--max_old_space_size=8192'
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    ports:
      - '9000:9000'
    volumes:
      - .:/repo
      - node_modules:/repo/node_modules

  mermaid-docs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /repo
    command: ['sh', '-lc', 'pnpm install && ./run docs:dev']
    environment:
      NODE_OPTIONS: '--max_old_space_size=8192'
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    ports:
      - '3333:3333'
    volumes:
      - .:/repo
      - node_modules:/repo/node_modules

volumes:
  node_modules:
