FROM node:22.12.0-alpine3.19@sha256:40dc4b415c17b85bea9be05314b4a753f45a4e1716bb31c01182e6c53d51a654

ARG PNPM_VERSION=10.4.1

WORKDIR /repo

RUN apk add --no-cache \
    bash \
    build-base \
    cairo-dev \
    giflib-dev \
    git \
    libjpeg-turbo-dev \
    pango-dev \
    pixman-dev \
    python3 \
  && npm install -g pnpm@${PNPM_VERSION}

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* .npmrc* ./
COPY packages/*/package.json ./packages/
COPY packages/mermaid/src/docs/package.json ./packages/mermaid/src/docs/
COPY tests/*/package.json ./tests/
COPY patches ./patches
RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_OPTIONS="--max_old_space_size=8192"
ENV MERMAID_PORT=9000

EXPOSE 9000 3333
