services:
  mermaid-app:
    image: ghcr.io/nicho2/mermaid:dev
    restart: unless-stopped
    working_dir: /repo
    environment:
      MERMAID_PORT: '9000'
      NODE_OPTIONS: '--max_old_space_size=8192'
    ports:
      - '9000:9000'
    command: ['sh', '-lc', 'pnpm install --frozen-lockfile && pnpm dev']

  mermaid-docs:
    image: ghcr.io/nicho2/mermaid:dev
    restart: unless-stopped
    working_dir: /repo
    environment:
      NODE_OPTIONS: '--max_old_space_size=8192'
    ports:
      - '3333:3333'
    command: ['sh', '-lc', 'pnpm install --frozen-lockfile && ./run docs:dev']
